name: Executar script GPT

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Ou a versão do Python desejada

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se você tiver um arquivo de requisitos

    - name: Executar script GPT
      run: python script.py  # Ou o nome do seu script

