name: Executar script GPT

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv gpt-env
        source gpt-env/bin/activate
        python -m pip install -r requirements.txt

    - name: Executar script GPT
      run: |
        source gpt-env/bin/activate
        python script.py  # Ou o nome do seu script
